dist: trusty
language: python

python:
  - "3.6"

# https://docs.travis-ci.com/user/gui-and-headless-browsers/
#addons:
#  chrome: stable

# https://benlimmer.com/2019/01/14/travis-ci-xvfb/
#services:
#  - xvfb

addons:
  apt:
    - google-chrome-stable
    - chromium-chromedriver

before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox
